package com.velox.framework.file.common.error;

public enum FileErrorCode {
    DISABLED("FILE_CAPABILITY_DISABLED"),
    CLIENT_NOT_FOUND("FILE_CLIENT_NOT_FOUND"),
    UNSUPPORTED_STORAGE("FILE_STORAGE_UNSUPPORTED"),
    OPERATION_NOT_SUPPORTED("FILE_OPERATION_NOT_SUPPORTED"),
    OPERATION_FAILED("FILE_OPERATION_FAILED"),
    REGISTRATION_CONFLICT("FILE_STORAGE_REGISTRATION_CONFLICT"),
    CLIENT_ID_REQUIRED("FILE_CLIENT_ID_REQUIRED"),
    CLIENT_CONFIG_REQUIRED("FILE_CLIENT_CONFIG_REQUIRED"),
    CLIENT_CONFIG_CLASS_REQUIRED("FILE_CLIENT_CONFIG_CLASS_REQUIRED"),
    CLIENT_CREATOR_REQUIRED("FILE_CLIENT_CREATOR_REQUIRED"),
    STORAGE_REQUIRED("FILE_STORAGE_REQUIRED"),
    TEMP_FILE_CREATE_FAILED("FILE_TEMP_FILE_CREATE_FAILED");

    private final String code;

    FileErrorCode(String code) {
        this.code = code;
    }

    public String code() {
        return code;
    }
}
